FROM golang:1.8
RUN apt-get -qq update && apt-get install -y cmake build-essential pkg-config openssl zlib1g curl wget && \
    curl -L -o zlib-1.2.11.tar.gz http://zlib.net/zlib-1.2.11.tar.gz && \
    tar xzvf zlib-1.2.11.tar.gz && \
    cd zlib-1.2.11 && \
    ./configure && \
    make && make install && \
    cd / && \
    rm -rf zlib-1.2.11 && \
    curl -L -o openssl-1.0.2h.tar.gz https://openssl.org/source/openssl-1.0.2h.tar.gz && \
    tar xzvf openssl-1.0.2h.tar.gz && \
    cd openssl-1.0.2h && \
    ./config --prefix=/usr \
             --openssldir=/etc/ssl \
             --libdir=lib \
             shared \
             zlib-dynamic && \
    make depend && \
    make && make install && \
    cd / && \
    rm -rf openssl-1.0.2h && \
    rm openssl-1.0.2h.tar.gz && \
    curl -L -o http-parser.tar.gz -z http-parser.tar.gz https://github.com/nodejs/http-parser/archive/v2.7.0.tar.gz && \
    tar xzvf http-parser.tar.gz && \
    cd http-parser-2.7.0 && \
    PREFIX=/usr make package && PREFIX=/usr/ make install && ls /usr/include/ && ls /usr/lib/ && \
    curl -L -o libssh.tar.gz -z libssh.tar.gz https://www.libssh2.org/download/libssh2-1.4.2.tar.gz && \
    tar xzvf libssh.tar.gz && \
    cd libssh2-1.4.2 && \
    ./configure && \
    make && make install && \
    cd / && \
    rm -rf libssh2-1.4.2 && \
    curl -L -o v0.24.1.tar.gz -z v0.24.1.tar.gz https://github.com/libgit2/libgit2/archive/v0.24.1.tar.gz && \
    tar xzvf v0.24.1.tar.gz && \
    cd libgit2-0.24.1 && \
    pwd && \
    mkdir build && \
    cd build && \
    pwd && \
    cmake .. \
        -DCMAKE_INSTALL_PREFIX=/usr/ \
        -DTHREADSAFE=ON \
        -DBUILD_CLAR=OFF \
        && \
    cmake --build . --target install && \
    cd - && \
    rm -rf libgit2-0.22.0 && \
    cd ${GOPATH} && \
    go get -u github.com/Masterminds/glide
ENTRYPOINT ["go"]
