FROM golang:1.6
RUN apt-get -qq update && apt-get install -y cmake build-essential pkg-config openssl zlib1g curl wget && \
    curl -o zlib-1.2.8.tar.gz -z zlib-1.2.8.tar.gz http://zlib.net/zlib-1.2.8.tar.gz && \
    tar xzvf zlib-1.2.8.tar.gz && \
    cd zlib-1.2.8 && \
    ./configure && \
    make && make install && \
    curl -o openssl-1.0.2h.tar.gz -z openssl-1.0.2h.tar.gz https://openssl.org/source/openssl-1.0.2h.tar.gz && \
    tar xzvf openssl-1.0.2h.tar.gz && \
    cd openssl-1.0.2h && \
    ./config --prefix=/usr \
             --openssldir=/etc/ssl \
             --libdir=lib \
             shared \
             zlib-dynamic && \
    make depend && \
    make && make install
ADD . /go/src/github.com/cpg1111/maestro/
WORKDIR /go/src/github.com/cpg1111/maestro/
RUN make get-deps && make && make install
ENV PATH $PATH:$GOPATH/bin
WORKDIR /go/src/github.com/cpg1111/maestro/
ENTRYPOINT ["maestro"]
