[Environment]
Exec=["docker pull cpg1111/maestro"]

[Project]
RepoURL="git@github.com:cpg1111/maestro.git"
CloneCMD="git clone"
AuthType="SSH"
SSHPrivKeyPath="~/.ssh/id_rsa"
SSHPubKeyPath="~/.ssh/id_rsa.pub"
Username="git"
Password=""
PromptForPWD=false

[[Services]]
Name="test"
Tag="0.0.1"
TagType=""
Path="."
BuildLogFilePath="./test.log"
BuildCMD=["make"]
TestCMD=["make test"]
CheckCMD=["docker ps -a"]
CreateCMD=["make docker"]
UpdateCMD=["make docker"]
DependsOn=[]
    [HealthCheck]
    Type="PTRACE_ATTACH"
    ExpectedCondition="nil"
    Retrys=3

[CleanUp]
AdditionalCMDs=["docker inspect maestro"]
InDaemon=false
    [[CleanUp.Artifacts]]
    RuntimeFilePath="./dist/maestro"
    SaveFilePath="/tmp/maestro"
