[Environment]
Exec=["docker pull cpg1111/maestro"]

[Project]
RepoURL="git@github.com:cpg1111/maestro.git"
CloneCMD="git clone"
AuthType="SSH"
SSHPrivKeyPath="~/.ssh/id_rsa"
SSHPubKeyPath="~/.ssh/id_rsa.pub"
Username="git"
Password=""
PromptForPWD=false

[[Services]]
Name="test"
Tag="0.0.1"
TagType=""
Path="."
BuildCMD="bash -c 'docker build -f Dockerfile_build -t maestro_build . && docker run -v $(pwd)/dist:/opt/bin/ && docker build -t cpg1111/maestro .'"
TestCMD="go test -v ./..."
CheckCMD="docker ps -a"
CreateCMD="docker push cpg1111/maestro"
UpdateCMD="docker rm -f test && docker run -n test -d test"
DependsOn=[]
    [HealthCheck]
    Type="ptrace_attach"
    ExpectedCondition="nil"

[CleanUp]
AdditionalCMDs=["docker inspect cpg1111/maestro"]
InDaemon=false
    [[CleanUp.Artifacts]]
    RuntimeFilePath="./dist/maestro"
    SaveFilePath="/tmp/maestro"
